// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5c8edpgG0yB93yk8pSkFWtrrporPqD3g',
    appId: '1:431081904894:web:c75facdba7b12726d723af',
    messagingSenderId: '431081904894',
    projectId: 'ajhman-22ca0',
    authDomain: 'ajhman-22ca0.firebaseapp.com',
    storageBucket: 'ajhman-22ca0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9NRgEYpqSsfNEF0kTCFwOmZav1dvvUnY',
    appId: '1:431081904894:android:9ba75a094da67bfed723af',
    messagingSenderId: '431081904894',
    projectId: 'ajhman-22ca0',
    storageBucket: 'ajhman-22ca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKQ8eVbWjAh500ebUDdGTHf6mPAiCClnM',
    appId: '1:431081904894:ios:8e17e2920e4dc860d723af',
    messagingSenderId: '431081904894',
    projectId: 'ajhman-22ca0',
    storageBucket: 'ajhman-22ca0.appspot.com',
    iosBundleId: 'com.example.ajhman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKQ8eVbWjAh500ebUDdGTHf6mPAiCClnM',
    appId: '1:431081904894:ios:8e17e2920e4dc860d723af',
    messagingSenderId: '431081904894',
    projectId: 'ajhman-22ca0',
    storageBucket: 'ajhman-22ca0.appspot.com',
    iosBundleId: 'com.example.ajhman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5c8edpgG0yB93yk8pSkFWtrrporPqD3g',
    appId: '1:431081904894:web:0d52f84d534f65f6d723af',
    messagingSenderId: '431081904894',
    projectId: 'ajhman-22ca0',
    authDomain: 'ajhman-22ca0.firebaseapp.com',
    storageBucket: 'ajhman-22ca0.appspot.com',
  );

}